/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_rhtsjz_jse_jni_HelloJNICpp */

#ifndef _Included_com_github_rhtsjz_jse_jni_HelloJNICpp
#define _Included_com_github_rhtsjz_jse_jni_HelloJNICpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_rhtsjz_jse_jni_HelloJNICpp
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_rhtsjz_jse_jni_HelloJNICpp_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
